### ISSUE TITLE
Add `NCAR/cesm-lens-aws` repo to xdevbot watchlist 

### ISSUE THREAD

**Issue by andersy005** [NCAR/xdev#117]
I created the issue (#116) from the command line using GitHub CLI and the encoding of text in the body of the issue appears to have resulted into errors. This PR is meant to amend #111 

/add-repo campaign:eocb repo:NCAR/cesm-lens-aws

**Comment by andersy005** [comment]
Okay... Something weird is going on in the CI script... I am going to look into it

**Comment by kmpaul** [comment]
Thanks!
