### ISSUE TITLE
We are Xdev!  Blog Post

### ISSUE THREAD

**Issue by kmpaul** [NCAR/xdev#42]
Need to finish...  get input from Matt Long.

**Comment by bonnland** [comment]
https://github.com/utterance/utterances

This is a possible alternative to adding "Disqus" comments to the xdev blog.

**Comment by kmpaul** [comment]
Need to clean up my fork and merge in to get input from @matt-long.

**Comment by kmpaul** [comment]
Also curious how deep this post should go, or whether a "deeper" article should be a separate post.

**Comment by kmpaul** [comment]
See #62

**Comment by kmpaul** [comment]
Closed with merge of #62
