### ISSUE TITLE
Xarray Documentation Plan

### ISSUE THREAD

**Issue by jukent** [NCAR/xdev#50]
Is there a template from Xarray functions with good functionality? Find a model so these can be consistent, talk to Deepak.

List of functions used in tutorials (to start with -- please add other functions that are commonly used and check which of these are adequately documented):
Xarray.open_dataset
xarray.DataArray.isel
xarray.DataArray.sel
xarray.DataArray.where
xarray.DataSet.groupby
Xarray.DataSet.mean
Xarray.apply_ufunc

Each XDev member with interest in learning Xarray can pick one of these functions, then we have a 10 minute presentation on it during meetings. (One person a meeting?)

**Comment by jukent** [comment]
https://docs.google.com/spreadsheets/d/1eiKXCt_rJbxoeLw4D2bAiPOEN8jxXKJjWuOBgbNFQdU/edit#gid=0

**Comment by kmpaul** [comment]
@jukent Let's do this "as we go" with our Xarray development sessions (starting tomorrow!).
