### ISSUE TITLE
Converting NCL code to Python

### ISSUE THREAD

**Issue by kmpaul** [NCAR/xdev#51]
Working with a number of people to convert NCL to Python.

**Comment by kmpaul** [comment]
I will share NCL gallery statistics with everyone.

**Comment by mnlevy1981** [comment]
I only noticed this issue because I did [an egosearch](https://github.com/NCAR/xdev/projects/1?card_filter_query=assignee%3Amnlevy1981) on the backlog queue, but I think this can be closed in favor of the specific issues we are working on alongside the geoCAT team.
