### ISSUE TITLE
CI Proxy Service

### ISSUE THREAD

**Issue by kmpaul** [NCAR/xdev#58]
As discussed with Mick Cody and Sidd Ghosh, there is a way forward here that involves creating a proxy service, running on Cheyenne, that can query a publicly running CI service.  A general sketch looks like:

1. CI is setup for a repo (like CircleCI)
2. A CI job is triggered on the repo, which launches the CI jobs/steps on the CI VM
3. One of the steps in the CI job is to send CI job information to a "proxy service" (running where? heroku?)
4. A cron-job, running on Cheyenne, periodically queries the "proxy service"
   - If the proxy service has a job waiting for it, then it sends the job back to the cron-job as its response
  - If the proxy service has no jobs in its queue, then it sends back an "empty" response
5. If the cron-job gets a non-empty response, it runs the job.
6. When the job is complete, the result is sent back to the proxy service
7. The proxy service sense the result back to the CI job
8. The CI job completes with the appropriate success/failure based on the Cheyenne test results

Can we mock up something like this fairly quickly?  A heroku bot could act as the proxy.  Can we do something fairly simple _and_ generic?  Perhaps more importantly, **has this been done before**?

**Comment by andersy005** [comment]
@kmpaul, I thought [Continuous Integration and Delivery for HPC](http://delivery.acm.org/10.1145/3220000/3219147/a6-Sampedro.pdf?ip=67.173.253.169&id=3219147&acc=OA&key=4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E00EED0A70DC5CC26&__acm__=1574739227_57fcc87c5f257b6e3d5a0537f2dd4208) paper might be of interest to you

**Comment by kmpaul** [comment]
@andersy005 @bonnland Shall we close this issue?  It doesn't sound like we need to move forward with this.

**Comment by kmpaul** [comment]
I'm going to close this issue, since it does not seem like we need to move forward with it any more.
