### ISSUE TITLE
Xdev Proposal Plan

### ISSUE THREAD

**Issue by kmpaul** [NCAR/xdev#60]
We need a plan for how to move forward into the future as a team that assists scientists in developing analysis workflows:

- Develop collaborations with "nearby" scientists to develop technology that assists and makes possible _curiosity-driven data analysis_ workflows.
- Develop a process for starting and ending short-term prototyping projects with these scientists, perhaps internally for the first quarter of 2020.
- Reach out to scientists working on new diagnostic tools for the model.
- Need to help scientists take over ownership of our prototypes when the project ends.
- Need to invest in Xarray.
- Need to watch our level of support vs development activities.
- Move forward as originally planned, with these caveats.
- We should model good behavior in our tutorial.

**Comment by kmpaul** [comment]
See this [Proposal Template](https://docs.google.com/document/d/11pzRZR1VeDRW2oOb75qsFSd7BpOlyOqCeCPMOW1gMoY/edit?usp=sharing)

**Comment by kmpaul** [comment]
Thanks @jukent for the template!

**Comment by kmpaul** [comment]
Until we decide if we are genuinely moving to a formal proposal process, I am going to close this issue.  But we should bookmark it to reopen it in the future, if needed.

**Comment by jukent** [comment]
It sounds like the formal template is something that is easiest to form as we are working on our first projects.

**Comment by kmpaul** [comment]
Yeah.  I think so.

**Comment by andersy005** [comment]
Can we convert the [existing google doc template](https://docs.google.com/document/d/11pzRZR1VeDRW2oOb75qsFSd7BpOlyOqCeCPMOW1gMoY/edit?usp=sharing) into a markdown file and host the markdown file in this repo?

**Comment by jukent** [comment]
Yes it can be. I think as we develop it, we can continue development in markdown. I can work on this on Friday if it is a priority.
