### ISSUE TITLE
JupyterHub Planning

### ISSUE THREAD

**Issue by kmpaul** [NCAR/xdev#61]
Let's list the things we need to discuss in meeting tomorrow with Jared et al.

@NCAR/xdev

**Comment by andersy005** [comment]
- Create a global `notebook-gallery` kernel on the Hub. It would be nice to give us (@NCAR/xdev) write permissions (by changing the access control lists I believe) to this kernel conda environment. Xref: https://github.com/NCAR/notebook-gallery/issues/34

**Comment by kmpaul** [comment]
- When will the JupyterHub allow spawning on a login node?

**Comment by kmpaul** [comment]
- When will it be possible to spawn a Jupyter Lab session in a custom user environment?

**Comment by kmpaul** [comment]
- When will we have a system-wide Python environment for users (whether they access using JupyterHub or SSH)?

**Comment by andersy005** [comment]
> When will we have a system-wide Python environment for users (whether they access using JupyterHub or SSH)?

@bonnland took the created `conda` module (available on Cheyenne only as of today) for a test drive. He may have some input on whether this ready for wide usage.

**Comment by kmpaul** [comment]
Notes from 12/4/2019 Meeting:

- Brian: Would like something like Binder to demonstrate Notebooks to users (e.g., NCL scripts converted to Jupyter Notebooks)
- Kevin:  Look into NBGallery; Look for CISL Seminar in 2020
- Jared & Kevin:  We should prioritize the "mock Cheyenne" on the cloud environment.
- Q: Running on login node?  Maybe next week.  Looking into technology to do it easily.
- Q: System-wide Python environment?  Still trying to figure it out with Brian V.
- Kevin:  Will follow up on finding contractor funding for cloud developer?  Knows web-apps (webdev) very well.  Ask Joe and/or Rich for funding.
