### ISSUE TITLE
Overcoming deficiencies in our current workflow

### ISSUE THREAD

**Issue by kmpaul** [NCAR/xdev#68]
I'd like to discuss how better to organize ourselves and deal with deficiencies in our workflow.  To begin, I would like to explicitly declare what deficiencies we currently have in our workflow.

Personally, I believe that GitHub should be our primary organizational utility, with GitHub notifications being our primary means of communicating with each other and other collaborators.  However, GitHub notifications are good for some things, and bad for others.  

GitHub notifications are **good** for general developer communication, namely:

- informing you when someone else has an _issue_,
- informing you when someone else needs your input (@-mentions), and
- informing you when changes are made to software you are working on.

GitHub notifications are **bad** for:

- letting you know what the rest of the team is working on (i.e., transparency),
- letting you know what you should work on next (i.e., prioritization), and
- keeping you focused on the task currently at hand (i.e., focus).

I believe that the [Xdev Project Board](https://github.com/NCAR/xdev/projects/1) is very good for making our work _transparent_, but I still believe that we have a problem with _prioritization_ and _focus_.

I would like to open this issue to solicit two things:

1. What other deficiencies do we currently have with our workflow (i.e., other than _focus_ and _prioritization_)?
2. What solutions might exist to help with these deficiencies (e.g., tools or services)?

**Comment by kmpaul** [comment]
**Possible Solution for _Focus_: Multiple Project Boards**  

We could split our single Project Board up across multiple Project Boards, focusing work on specific, related tasks.  This would require adding features to the Xdev Bot.  We could still (for example) have one _master_ Project Board that aggregated all of our issues and PRs.

**Comment by kmpaul** [comment]
**Possible Solution for _Focus_ and _Prioritization_: ZenHub**

[ZenHub](https://www.zenhub.com/) is a GitHub App that can be installed (for free) with your GitHub account.  It allows you to create "workspaces" that link to multiple GitHub repositories.  It then gives you a "GitHub Project Board on steroids."  It adds the ability to define Epics (i.e., project tasks that span multiple issues and PRs), which helps with organizing and prioritizing our tasks.  Using multiple workspaces would be like having multiple Project Boards (see previous comment). 
 It would essentially replace the Xdev Project Board and the Xdev Bot.  

It appears to be good at organizing work that spans multiple repositories, but it gets slow when it tries to organize _lots_ of repositories into a "single workspace" (i.e., a single project board.)  Considering how many repositories we are spread across, this could be problematic.  I tried it out as a trial, and it seemed a little too slow for me.

**Comment by bonnland** [comment]
ZenHub looks promising.  Epics are really nice for organizing and coordinating stories.

Is it possible to have multiple boards with ZenHub, to reduce the number of repos per board?   The SAGE team has used multiple boards centered around different applications or projects, and it has worked out well.   It might not work out if we have a lot of overlap between projects.

**Comment by bonnland** [comment]
@kmpaul Adding a callout, hopefully in keeping with our Process!

**Comment by kmpaul** [comment]
Thanks, @bonnland!  You can have multiple boards with ZenHub.  They call them "Workspaces."  When I tried it out for a bit, I did try adding all of our repos to one board.  ZenHub _freaked out_!  And the response time was very slow.

So, I tried creating a "Workspace" that only contained our "cataloging" repos (i.e., all of our intake related repos), and it was still pretty slow.  I stopped trying it out, though, as it got a bit frustrating.

ZenHub's (and Scrum's) Epics are what I think of as "Projects," and I do think we could benefit from having different boards for different projects.  Which makes me think that the **Multiple Project Board** approach might actually be the most responsive.
