### ISSUE TITLE
ESM Diagnostics Challenge

### ISSUE THREAD

**Issue by kmpaul** [NCAR/xdev#69]
**Background:**

We are thinking about scoping out what the future of an ESM diagnostics package should look like.  In general, I believe that the package itself should be _agnostic_ with respect to the actual model used (e.g., CESM).  So, thinking about diagnostics from a general sense, I would say that such a package should have the following features:

- provides data _pipelines_ from ESM output to specific diagnostic products (e.g., images), with the option of saving intermediate states (e.g., climatologies)
- orchestrate multiple pipelines at once (i.e., _workflow orchestration_)
- _scale_ efficiently with the size of the input data
- leverage the same technology that can be used for interactive analysis (i.e., share the computation routines)

The Xdev Team (@NCAR/xdev) should expect this to be a significant effort that we contribute to over the next year or more.

**Issues:**

- What packages _already exist_ to provide the features described above?
- What features have I missed from the above list?
- Of existing packages that claim to do some of the necessary steps for ESM diagnostics, which ones can best integrate?

**Comment by kmpaul** [comment]
A few packages to look at:

- [ESMValTool](https://github.com/ESMValGroup/ESMValTool) for ESM computations
- [Cylc](https://github.com/cylc/cylc-flow) for workflow orchestration

And all of the packages linked from this awesome list:

[awesome-workflow-engines](https://github.com/meirwah/awesome-workflow-engines)

And, obviously, there is our own [xcollection](https://github.com/NCAR/xcollection).

**Comment by matt-long** [comment]
Curious why this issue has been closed. It still seems very relevant.

**Comment by kmpaul** [comment]
We are trying to clean up the Xdev project board and remove issues that don't pertain to actual work that needs to be done.  Perhaps we should keep this open as a placeholder, but it seems to have gone stale.  Is there a more pertinent *current* issue that we can replace this with?  Or can we make this issue (itself) more pertinent?

**Comment by matt-long** [comment]
This "issue" is really a whole research program. So in that sense, I see your point. I think we should be making progress on each of the elements here through developing prototypes.

**Comment by kmpaul** [comment]
I agree.  To that end, I am trying to identify more specific issues that we can address with prototypes or similar.

**Comment by kmpaul** [comment]
I should also point out that, in the past, we've created high-level issues like this to allow discussion and scoping of more specific projects, but I think that we have come to acknowledge that these kinds of issues just clutter our project board.  So, instead, I've been trying to encourage people to move these kinds of big-ticket items to "project specifications" (https://github.com/NCAR/xdev-projects).  And while I think that separation of high- and low-"resolution" issues is useful, I'm working on how to make these project specification documents more useful to the team.
