### ISSUE TITLE
Contact Bill Skamarock for MPAS Diagnostics

### ISSUE THREAD

**Issue by bonnland** [NCAR/xdev#72]
Bill Skamarock (https://staff.ucar.edu/users/skamaroc) is the chief scientist for MPAS.   I ran into him on the shuttle recently, and he is very interested in moving some of their code to python.   

Someone should reach out to him and let him know that we're trying to build a diagnostics framework that is usable by scientists using different simulation models at NCAR.

**Comment by kmpaul** [comment]
What is the status of this?  Did we ever hear anything back from Bill?
