### ISSUE TITLE
Create a twitter list with people of interest to Xdev

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/xdev#85]
From https://github.com/NCAR/xdev/pull/84#discussion_r458948704

> One additional possible use of twitter would be to create a publicly-available list of folks whose work is of interest to us -- such as Xdev members themselves (if they are have work-centric twitter accounts) and that large fraction of the Pangeo community you mention. I'm imagining something like Katharine Hayhoe's [_scientists who do climate_](https://twitter.com/i/lists/1053067173961326594) list but geared toward's Xdev's mission.

Assigning @kmpaul since he's the one with the keys to the account, but maybe we could all suggest accounts to add to the list in this ticket?

**Comment by kmpaul** [comment]
@mnlevy1981:  How would you like this to work?  Would you want to see "Who is following @NCARXdev on Twitter?" or something different?

**Comment by kmpaul** [comment]
...or would you want something like a "subsection" of the "Who is following @NCARXdev on Twitter?"  A subsection might need to be hand-molded, which could be difficult.

**Comment by mnlevy1981** [comment]
Twitter offers a feature called [lists](https://help.twitter.com/en/using-twitter/twitter-lists) that basically creates an ad-free time-line that only consists of tweets and re-tweets made by the people on the list (the [scientists who do climate](https://twitter.com/i/lists/1053067173961326594) link I mentioned above is an example of this feature). I would suggest having the XDev account [create it](https://twitter.com/i/lists/create) and maintain it... basically any user would be able to subscribe to it (and then have an easy way to keep up with all of those accounts), but only the Xdev account would control whose tweets actually appear on the list. I'm struggling to come up with a strawman title for the list, but something like "XDev Interests" maybe? A starting point could be

* some NCAR accounts (NCARXdev itself, NCAR Science, NCAR CISL, etc)
* some individuals (XDev members, Pangeo folks, etc)
* some miscellaneous (do python packages like numpy, xarray, dask, etc have twitter accounts to announce things on?)

There is an initial cost to getting the list going, and then it may need to be updated occasionally as accounts are added / removed.

**Comment by mnlevy1981** [comment]
I wanted to highlight the difference between "accounts on the list" and "accounts subscribed to the list" in the post above, but omitted it by mistake. It might be best to explain via example: I have a personal twitter account that rarely delves into anything work-related (the last few tweets ranged from Adam Sandler to how glad I am that the NFL team I grew up rooting for is finally dropping its extremely racist name to Hamilton being on Disney+), so my account should not be on the list (i.e. visible as something deemed relevant to XDev) but I would want to subscribe to the list (i.e. see all the posts made from the other accounts).

**Comment by kmpaul** [comment]
I see.  The old man here is learning something about this Tweeter thingy.  

If I subscribe to a list, do tweets from "accounts on the list" show up in my timeline like other tweets?  If so, does that mean that lists are essentially "account aggregations" (i.e., subscribe to just 1 list and effectively be subscribed to many accounts)?

**Comment by mnlevy1981** [comment]
> If I subscribe to a list, do tweets from "accounts on the list" show up in my timeline like other tweets?

Nope, it's completely separate. You have to navigate to the lists part of the site to see those tweets.

**Comment by kmpaul** [comment]
I see.  So no clutter, but then how is it different from just going to a specific accounts timeline directly?

**Comment by kmpaul** [comment]
Ok.  Thanks, @mnlevy1981, for the video demo.  That looks like a nice service that we can provide to both *ourselves* and to the community.

Let's start the process of accumulating a list of accounts that we want to add to the list:

@CoiledHQ
@dask_dev
@xarray_dev
@numpy_team
@pangeo_data
@ProjectJupyter
@NCARXdev 

Who else should be on the list?

**Comment by kmpaul** [comment]
@NCAR/xdev
